[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tier"
version = "0.1.0.dev1"
description = "Python Versioning CLI"
authors = [ "Josh Wycuff <Joshua.Wycuff@turner.com>",]
license = "MIT"
readme = "README.md"
[[tool.poetry.packages]]
include = "tier"

[tool.poetry.dependencies]
python = ">=3.8,<4"
toml = "^0.10.2"

[tool.poetry.scripts]
tier = "tier.main:main"

[tool.poetry.dependencies.jw-meta]
develop = true
path = "../jw-meta"

[tool.poetry.dependencies.jw-datatools]
develop = true
path = "../jw-datatools"

[tool.poetry.dependencies.jw-itertools]
develop = true
path = "../jw-itertools"

[tool.poetry.dependencies.jw-graph]
develop = true
path = "../jw-graph"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
coverage = "^6.5.0"
