[tool.poetry]
name = "jw-meta"
version = "0.0.0"
description = "JW Meta"
authors = ["Josh Wycuff <Joshua.Wycuff@turner.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "jw_meta"}]

[tool.poetry.dependencies]
python = ">=3.8,<4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
